persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: "/mnt/shared_storage_1/downloads"
    hostPathType: DirectoryOrCreate
    targetSelector:
      main:
        main:
          mountPath: /config
          type: hostPath
          hostPath: "/mnt/shared_storage_1/downloads"
          hostPathType: DirectoryOrCreate
      exportarr:
        exportarr:
          mountPath: /config
          readOnly: true
  shared:
    enabled: true
    type: hostPath
    hostPath: "/mnt/shared_storage_1/downloads"
    hostPathType: DirectoryOrCreate
    targetSelector:
      main:
        main:
          type: hostPath
          hostPath: "/mnt/shared_storage_1/downloads"
          mountPath: "/shared"
          hostPathType: DirectoryOrCreate
      exportarr:
        exportarr:
          type: hostPath
          hostPath: "/mnt/shared_storage_1/downloads"
          mountPath: /shared
          readOnly: true
          hostPathType: DirectoryOrCreate
          
service:
  main:
    type: LoadBalancer
    loadBalancerIP: 10.10.10.250
    annotations:
      metallb.universe.tf/allow-shared-ip: readarr
    ports:
      main:
        port: 80
  metrics:
    enabled: true
    type: ClusterIP
    targetSelector: exportarr
    ports:
      metrics:
        enabled: true
        port: 8788
        targetSelector: exportarr
